<?php

namespace MenuBundle\Repository;

/**
 * lienMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lienMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
