<?php

namespace PageBundle\Repository;

/**
 * ColRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColRepository extends \Doctrine\ORM\EntityRepository
{
}
