<?php

namespace PageBundle\Repository;

/**
 * ColsModulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColsModulesRepository extends \Doctrine\ORM\EntityRepository
{
}
