<?php

namespace PageBundle\Repository;

/**
 * DispositionRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispositionRowRepository extends \Doctrine\ORM\EntityRepository
{
}
