<?php

namespace PageBundle\Repository;

/**
 * keyWordsPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class keyWordsPageRepository extends \Doctrine\ORM\EntityRepository
{
}
