<?php

namespace PageBundle\Repository;

/**
 * keyWordsArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class keyWordsArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
