<?php

namespace PageBundle\Repository;

/**
 * keyWordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class keyWordsRepository extends \Doctrine\ORM\EntityRepository
{
}
