<?php

namespace PageBundle\Repository;

/**
 * TypeRowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRowRepository extends \Doctrine\ORM\EntityRepository
{
}
