imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@HomeBundle/Resources/config/services.yml" }
    - { resource: "@PageBundle/Resources/config/services.yml" }
    - { resource: "@ArticleBundle/Resources/config/services.yml" }
    - { resource: "@ModuleBundle/Resources/config/services.yml" }
    - { resource: "@MenuBundle/Resources/config/services.yml" }
    - { resource: "@TemplateBundle/Resources/config/services.yml" }
    - { resource: "@CategoryBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AdminBundle\Entity\User
#    registration:
#        form:
#            type: AdminBundle\Form\Type\RegistrationType
#    profile:
#        form:
#            type: AdminBundle\Form\Type\ProfileType
#    group:
#        group_class: AdminBundle\Entity\Group
        
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['materialize_layout.html.twig'] 
    paths:
        '%kernel.root_dir%/../src/AdminBundle/Resources/views': AdminViews
        '%kernel.root_dir%/../src/PageBundle/Resources/views': PageViews

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
kms_froala_editor:
  language: "fr"
  toolbarInline: false
  tableColors: [ "#FFFFFF", "#FF0000" ]
  includeJQuery: false
  includeCodeMirror: false
  includeFontAwesome: false
  includeJS: false
  includeCSS: false
  pluginsDisabled: [ "mediaManager", "video", "fullscreen" ]
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles: [ ]
    filters:
        cssrewrite: ~
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed.jar"        
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        lessphp:
            file: "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"   
            apply_to: ".less$"
    assets:
        jquery_js:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.min.js"            
            filters: [?yui_js]
            output: js/vendor/jquery.min.js
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css
            filters:
#                - lessphp
#                - cssrewrite
            output: css/vendor/bootstrap/bootstrap.min.css
        froala_css:
            inputs:
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/froala_style.min.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/froala_editor.min.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/char_counter.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/code_view.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/colors.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/emoticons.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/file.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/fullscreen.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/image.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/image_manager.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/line_breaker.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/quick_insert.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/table.css
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/css/plugins/video.css
            output: css/vendor/froala/froala.min.css
        bootstrap_js:
            inputs:
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/util.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dist/tab.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
            output: js/vendor/bootstrap/bootstrap.js
        froala_js:
            inputs:
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/froala_editor.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/align.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/char_counter.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/code_beautifier.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/code_view.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/colors.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/emoticons.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/entities.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/file.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/font_family.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/font_size.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/fullscreen.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/image.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/image_manager.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/inline_style.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/line_breaker.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/link.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/lists.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/paragraph_format.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/paragraph_style.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/quick_insert.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/quote.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/table.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/save.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/url.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/plugins/video.min.js
                - %kernel.root_dir%/../vendor/kms/froala-editor-bundle/Resources/public/froala_editor_2.3.4/js/languages/fr.js
            output: js/vendor/froala/froala.min.js