template_template:
    resource: "@TemplateBundle/Controller/TemplateController.php"
    type:     annotation

menu_lien_menu:
    resource: "@MenuBundle/Controller/lienMenuController.php"
    type:     annotation

menu_menu:
    resource: "@MenuBundle/Controller/MenuController.php"
    type:     annotation

template:
    resource: "@TemplateBundle/Controller/"
    type:     annotation
    prefix:   /

menu:
    resource: "@MenuBundle/Controller/"
    type:     annotation
    prefix:   /

article_article:
    resource: "@ArticleBundle/Controller/ArticleController.php"
    type:     annotation

module:
    resource: "@ModuleBundle/Controller/"
    type:     annotation
    prefix:   /

article:
    resource: "@ArticleBundle/Controller/"
    type:     annotation
    prefix:   /

kms_froala_editor:
    resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    prefix:   /froalaeditor
    
page:
    resource: "@PageBundle/Controller/"
    type:     annotation
    prefix:   /admin/page/

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_security_login:
    path:      /admin/login
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }