services:
    module_service:
        class: ModuleBundle\Services\ModuleService
    module.routing_loader:
        class: ModuleBundle\Routing\AdvancedLoader
        tags:
            - { name: routing.loader }