<?php

namespace ModuleBundle\Repository;

/**
 * HTMLModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HTMLModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
