<?php

namespace ModuleBundle\CustomModules\HtmlModuleRepository;

/**
 * ImageModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
