<?php

namespace ModuleBundle\CustomModules\HtmlModule\Repository;

/**
 * HtmlModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HtmlModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
